# 服务器配置
server:
  port: 8080

# Spring Boot 应用配置
spring:
  application:
    name: railway-management-system
  # 数据库配置 (请替换为您的实际配置)
  datasource:
    url: jdbc:mysql://localhost:3306/railway_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Redis 配置 (请替换为您的实际配置)
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # Enable camelCase mapping
  mapper-locations: classpath*:mapper/*.xml # Optional: If you use XML mappers
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS

logging:
  level:
    # 设置根日志级别为INFO
    root: info
    # 为您的项目包设置更详细的DEBUG级别，方便开发调试
    com.railway.management: debug

  # 日志输出到文件
  file:
    # 文件路径，可以是相对路径或绝对路径
    name: logs/railway-management.log


# SpringDoc OpenAPI (Swagger) 配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html # 访问路径
  api-docs:
    path: /v3/api-docs
  info:
    title: 铁路管理系统 API
    description: "铁路管理系统后端服务API接口文档"
    version: "1.0.0"


# 存储服务配置 (local 或 oss)
storage:
  type: local
  local:
    # 注意：路径末尾最好带上斜杠
    upload-path: D:/uploads/ # 文件存储的物理路径 (请根据您的服务器环境修改)
    access-path: /uploads    # 外部访问的URL前缀

# 如果您不再使用OSS，可以注释或删除以下配置
# aliyun:
#   oss:
#     endpoint: your-oss-endpoint
#     access-key-id: your-access-key-id
#     access-key-secret: your-access-key-secret
#     bucket-name: your-bucket-name
