server:
  port: 8080
spring:
  profiles:
    active: dev

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # Enable camelCase mapping
  mapper-locations: classpath*:mapper/*.xml # Optional: If you use XML mappers
