server:
  port: 8080
spring:
  profiles:
    active: dev
  data:
    redis:
      host: your_redis_host
      port: your_redis_port
      password: your_redis_password
      database: 0  # The default database is 0, change if needed
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # Enable camelCase mapping
  mapper-locations: classpath*:mapper/*.xml # Optional: If you use XML mappers
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS

