# 服务器配置
server:
  port: 8080

# Spring Boot 应用配置
spring:
  application:
    name: railway-management-system
  # 数据库配置 (请替换为您的实际配置)
  datasource:
    url: jdbc:mysql://localhost:3306/railway_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Redis 配置 (请替换为您的实际配置)
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # Enable camelCase mapping
  mapper-locations: classpath*:mapper/*.xml # Optional: If you use XML mappers
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS


# SpringDoc OpenAPI (Swagger) 配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html # 访问路径
  api-docs:
    path: /v3/api-docs
  info:
    title: 铁路管理系统 API
    description: "铁路管理系统后端服务API接口文档"
    version: "1.0.0"
