package com.railway.managementsystem.user.dto;

import lombok.Data;

@Data
public class LoginRequest {
    private String username;
    private String password;

    // Getters and setters are generated by Lombok's @Data
    // If not using Lombok, you'd need to add them manually:
    // public String getUsername() { ... }
    // public String getPassword() { ... }
}